"""empty message

Revision ID: 2da9a633d023
Revises: 6f86b692dc1a
Create Date: 2018-07-07 19:01:49.613308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da9a633d023'
down_revision = '6f86b692dc1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('original', sa.String(length=128), nullable=False),
    sa.Column('thumb_big', sa.String(length=128), nullable=False),
    sa.Column('thumb_normal', sa.String(length=128), nullable=False),
    sa.Column('thumb_small', sa.String(length=128), nullable=False),
    sa.Column('thumb_mini', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_table('profile_pictures')
    # ### end Alembic commands ###
