"""empty message

Revision ID: 3f6b1db3140a
Revises: 2da9a633d023
Create Date: 2018-07-08 15:00:26.491700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f6b1db3140a'
down_revision = '2da9a633d023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('original', sa.String(length=128), nullable=False),
    sa.Column('thumb_big', sa.String(length=128), nullable=False),
    sa.Column('thumb_normal', sa.String(length=128), nullable=False),
    sa.Column('thumb_small', sa.String(length=128), nullable=False),
    sa.Column('thumb_mini', sa.String(length=128), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_pictures')
    # ### end Alembic commands ###
