"""empty message

Revision ID: 44b244c5cde3
Revises: aa95dcb42fc9
Create Date: 2018-06-14 16:36:08.732460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44b244c5cde3'
down_revision = 'aa95dcb42fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_tokens')
    op.add_column('registration_tokens', sa.Column('expires_in', sa.Integer(), nullable=False))
    op.add_column('registration_tokens', sa.Column('issued_at', sa.Integer(), nullable=False))
    op.drop_column('registration_tokens', 'created_at')
    op.drop_column('registration_tokens', 'expiration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_tokens', sa.Column('expiration', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('registration_tokens', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('registration_tokens', 'issued_at')
    op.drop_column('registration_tokens', 'expires_in')
    op.create_table('refresh_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='refresh_tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='refresh_tokens_pkey'),
    sa.UniqueConstraint('token', name='refresh_tokens_token_key')
    )
    # ### end Alembic commands ###
