"""empty message

Revision ID: 62487a724315
Revises: e2e8b745a337
Create Date: 2018-04-17 15:53:59.529241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62487a724315'
down_revision = 'e2e8b745a337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('phone_number', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('token')
    )
    op.drop_constraint('phone_tokens_user_id_fkey', 'phone_tokens', type_='foreignkey')
    op.drop_column('phone_tokens', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_tokens', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('phone_tokens_user_id_fkey', 'phone_tokens', 'users', ['user_id'], ['id'])
    op.drop_table('registration_tokens')
    # ### end Alembic commands ###
