"""empty message

Revision ID: 6680aa8088d6
Revises: db164f22e78a
Create Date: 2018-04-17 19:07:07.107735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6680aa8088d6'
down_revision = 'db164f22e78a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('admin_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'groups', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'admin_id')
    # ### end Alembic commands ###
