"""empty message

Revision ID: 87b5e948a78d
Revises: cdaebff4fc44
Create Date: 2018-04-17 20:55:08.854989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87b5e948a78d'
down_revision = 'cdaebff4fc44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('shares_cell_phone', sa.Boolean(), nullable=True))
    op.add_column('group_members', sa.Column('shares_home_phone', sa.Boolean(), nullable=True))
    op.add_column('group_members', sa.Column('shares_office_phone', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_members', 'shares_office_phone')
    op.drop_column('group_members', 'shares_home_phone')
    op.drop_column('group_members', 'shares_cell_phone')
    # ### end Alembic commands ###
