"""empty message

Revision ID: a9004edf0170
Revises: 44b244c5cde3
Create Date: 2018-06-14 16:59:30.185177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9004edf0170'
down_revision = '44b244c5cde3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_join_codes', sa.Column('expires_in', sa.Integer(), nullable=False))
    op.add_column('group_join_codes', sa.Column('issued_at', sa.Integer(), nullable=False))
    op.drop_column('group_join_codes', 'created_at')
    op.drop_column('group_join_codes', 'updated_at')
    op.drop_column('group_join_codes', 'expiration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_join_codes', sa.Column('expiration', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('group_join_codes', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('group_join_codes', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('group_join_codes', 'issued_at')
    op.drop_column('group_join_codes', 'expires_in')
    # ### end Alembic commands ###
