"""empty message

Revision ID: b3fbe2a67c20
Revises: 6680aa8088d6
Create Date: 2018-04-17 19:27:29.847370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3fbe2a67c20'
down_revision = '6680aa8088d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_members', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('group_members', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('id', sa.INTEGER(), nullable=False))
    op.alter_column('group_members', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
