"""empty message

Revision ID: b98aaee504d6
Revises: a9004edf0170
Create Date: 2018-07-07 01:33:26.827512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b98aaee504d6'
down_revision = 'a9004edf0170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('addresses_card_id_fkey', 'addresses', type_='foreignkey')
    op.create_foreign_key(None, 'addresses', 'cards', ['card_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('cards_user_id_fkey', 'cards', type_='foreignkey')
    op.create_foreign_key(None, 'cards', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('group_join_codes_group_id_fkey', 'group_join_codes', type_='foreignkey')
    op.create_foreign_key(None, 'group_join_codes', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.add_column('group_members', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.drop_constraint('group_members_user_id_fkey', 'group_members', type_='foreignkey')
    op.drop_constraint('group_members_group_id_fkey', 'group_members', type_='foreignkey')
    op.create_foreign_key(None, 'group_members', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'group_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('groups_admin_id_fkey', 'groups', type_='foreignkey')
    op.drop_column('groups', 'admin_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('groups_admin_id_fkey', 'groups', 'users', ['admin_id'], ['id'])
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_foreign_key('group_members_group_id_fkey', 'group_members', 'groups', ['group_id'], ['id'])
    op.create_foreign_key('group_members_user_id_fkey', 'group_members', 'users', ['user_id'], ['id'])
    op.drop_column('group_members', 'is_admin')
    op.drop_constraint(None, 'group_join_codes', type_='foreignkey')
    op.create_foreign_key('group_join_codes_group_id_fkey', 'group_join_codes', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key('cards_user_id_fkey', 'cards', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.create_foreign_key('addresses_card_id_fkey', 'addresses', 'cards', ['card_id'], ['id'])
    # ### end Alembic commands ###
