"""empty message

Revision ID: ee944a82a32e
Revises: 008ffde33fe5
Create Date: 2018-04-17 14:35:24.832779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee944a82a32e'
down_revision = '008ffde33fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_tokens', sa.Column('expiration', sa.DateTime(), nullable=True))
    op.add_column('phone_tokens', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'phone_tokens', 'users', ['user_id'], ['id'])
    op.drop_column('phone_tokens', 'new_phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_tokens', sa.Column('new_phone_number', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'phone_tokens', type_='foreignkey')
    op.drop_column('phone_tokens', 'user_id')
    op.drop_column('phone_tokens', 'expiration')
    # ### end Alembic commands ###
